server:
  port: 8080

spring:
  datasource:
    url:
    username:
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true